[package]
name = "sov-wasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
borsh = { version = "1", features = ["derive"] }
serde_json = "1.0"
serde = "1.0.196"

sov-modules-api = { git = "ssh://git@github.com/Sovereign-Labs/sovereign-sdk-wip.git", rev = "9451c4271f952edc57d6665041e74be783019ef3" }
sov-rollup-interface = { git = "ssh://git@github.com/Sovereign-Labs/sovereign-sdk-wip.git", rev = "9451c4271f952edc57d6665041e74be783019ef3" }

sov-risc0-adapter = { git = "ssh://git@github.com/Sovereign-Labs/sovereign-sdk-wip.git", rev = "9451c4271f952edc57d6665041e74be783019ef3" }
sov-mock-da = { git = "ssh://git@github.com/Sovereign-Labs/sovereign-sdk-wip.git", rev = "9451c4271f952edc57d6665041e74be783019ef3" }
sov-mock-zkvm = { git = "ssh://git@github.com/Sovereign-Labs/sovereign-sdk-wip.git", rev = "9451c4271f952edc57d6665041e74be783019ef3" }

stf-starter = { git = "ssh://git@github.com/Sovereign-Labs/sov-rollup-starter-wip.git", rev = "507721f83ab75b160ada6e9cd6959bc309fba52a" }

[dev-dependencies]

serde_json = { version = "1.0", features = ["std"] }
