[package]
name = "sov-wasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = { version = "0.2", features = ["serde-serialize"] }
serde_json = "1.0"
serde = { version = "1.0.196", features = ["derive"] }
borsh = { version = "1", features = ["derive"] }
serde-wasm-bindgen = "0.6.5"

sov-modules-api = { git = "ssh://git@github.com/Sovereign-Labs/sovereign-sdk-wip.git", rev = "5363dc5dc09c3a799e3458a0ca8d7542c52e108a" }
sov-risc0-adapter = { git = "ssh://git@github.com/Sovereign-Labs/sovereign-sdk-wip.git", rev = "5363dc5dc09c3a799e3458a0ca8d7542c52e108a" }
sov-mock-zkvm = { git = "ssh://git@github.com/Sovereign-Labs/sovereign-sdk-wip.git", rev = "5363dc5dc09c3a799e3458a0ca8d7542c52e108a" }




[dev-dependencies]
serde_json = { version = "1.0", features = ["std"] }
